api_platform:
    title: 'API Web Consult'
    description: 'Cette page liste les différents endpoints du service web du Web Consult'
    version: 1.0.0
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: false
    formats:
        #jsonld:
           #mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
