# config/routes.yaml
authentication_token:
    path: /api/login
    methods: ['POST']

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

swagger_ui:
    path: /api/docs
    controller: api_platform.swagger.action.ui
    methods: GET
    
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
